In [3]:
import pandas as pd
import matplotlib.pyplot as pit

In [38]:
cs=pd.read_csv("C:/Users/user/Desktop/imsi/data/01. cctv_in_Seoul.csv",encoding='utf-8')

In [6]:
xl=pd.read_excel("C:/Users/user/Desktop/imsi/data/01. population_in_Seoul.xls",endcoding='utf-8')

In [19]:
xl.rename(columns={xl.columns[0]:'구별'},inplace=True)

In [22]:
xl.head()

,구별,자치구,세대,인구,인구.1,인구.2,인구.3,인구.4,인구.5,인구.6,인구.7,인구.8,세대당인구,65세이상고령자
0,기간,자치구,세대,합계,합계,합계,한국인,한국인,한국인,등록외국인,등록외국인,등록외국인,세대당인구,65세이상고령자
1,기간,자치구,세대,계,남자,여자,계,남자,여자,계,남자,여자,세대당인구,65세이상고령자
2,2017.1/4,합계,4202888,10197604,5000005,5197599,9926968,4871560,5055408,270636,128445,142191,2.36,1321458
3,2017.1/4,종로구,72654,162820,79675,83145,153589,75611,77978,9231,4064,5167,2.11,25425
4,2017.1/4,중구,59481,133240,65790,67450,124312,61656,62656,8928,4134,4794,2.09,20764

In [23]:
pop_seoul=pd.read_excel("C:/Users/user/Desktop/imsi/data/01. population_in_Seoul.xls",header=2,usecols='B,D,G,J,N',endcoding='utf-8')

In [24]:
pop_seoul.head()

   자치구           계        계.1       계.2   65세이상고령자
0   합계  10197604.0  9926968.0  270636.0  1321458.0
1  종로구    162820.0   153589.0    9231.0    25425.0
2   중구    133240.0   124312.0    8928.0    20764.0
3  용산구    244203.0   229456.0   14747.0    36231.0
4  성동구    311244.0   303380.0    7864.0    39997.0

In [34]:
pop_seoul.rename(columns={pop_seoul.columns[0]:'구별',
                          pop_seoul.columns[1]:'인구수',
                          pop_seoul.columns[2]:'한국인',
                          pop_seoul.columns[3]:'외국인',
                          pop_seoul.columns[4]:'고령자'},inplace=True)

In [39]:
cs.rename(cs.columns[5]:'최근증가율',inplace=True)

SyntaxError: invalid syntax (<ipython-input-39-7b6896d8c58b>, line 1)

In [41]:
cs['최근증가율']=(cs['2016년']+cs['2015년']+cs['2014년'])/cs['2013년도 이전']*100
cs.sort_values(by='최근증가율',ascending=False).head()

    기관명    소계  2013년도 이전  2014년  2015년  2016년       최근증가율
22  종로구  1619        464    314    211    630  248.922414
9   도봉구   825        238    159     42    386  246.638655
12  마포구   980        314    118    169    379  212.101911
8   노원구  1566        542     57    451    516  188.929889
1   강동구  1010        379     99    155    377  166.490765

In [45]:
pop_seoul.drop([0],inplace=True)

In [47]:
pop_seoul

      구별       인구수       한국인      외국인      고령자
1    종로구  162820.0  153589.0   9231.0  25425.0
2     중구  133240.0  124312.0   8928.0  20764.0
3    용산구  244203.0  229456.0  14747.0  36231.0
4    성동구  311244.0  303380.0   7864.0  39997.0
5    광진구  372164.0  357211.0  14953.0  42214.0
6   동대문구  369496.0  354079.0  15417.0  54173.0
7    중랑구  414503.0  409882.0   4621.0  56774.0
8    성북구  461260.0  449773.0  11487.0  64692.0
9    강북구  330192.0  326686.0   3506.0  54813.0
10   도봉구  348646.0  346629.0   2017.0  51312.0
11   노원구  569384.0  565565.0   3819.0  71941.0
12   은평구  494388.0  489943.0   4445.0  72334.0
13  서대문구  327163.0  314982.0  12181.0  48161.0
14   마포구  389649.0  378566.0  11083.0  48765.0
15   양천구  479978.0  475949.0   4029.0  52975.0
16   강서구  603772.0  597248.0   6524.0  72548.0
17   구로구  447874.0  416487.0  31387.0  56833.0
18   금천구  255082.0  236353.0  18729.0  32970.0
19  영등포구  402985.0  368072.0  34913.0  52413.0
20   동작구  412520.0  400456.0  12064.0  56013.0
21   관악구  525515.0  507203.0  18312.0  68082.0
22   서초구  450310.0  445994.0   4316.0  51733.0
23   강남구  570500.0  565550.0   4950.0  63167.0
24   송파구  667483.0  660584.0   6899.0  72506.0
25   강동구  453233.0  449019.0   4214.0  54622.0
26   NaN       NaN       NaN      NaN      NaN

In [48]:
pop_seoul.drop([26],inplace=False)

      구별       인구수       한국인      외국인      고령자
1    종로구  162820.0  153589.0   9231.0  25425.0
2     중구  133240.0  124312.0   8928.0  20764.0
3    용산구  244203.0  229456.0  14747.0  36231.0
4    성동구  311244.0  303380.0   7864.0  39997.0
5    광진구  372164.0  357211.0  14953.0  42214.0
6   동대문구  369496.0  354079.0  15417.0  54173.0
7    중랑구  414503.0  409882.0   4621.0  56774.0
8    성북구  461260.0  449773.0  11487.0  64692.0
9    강북구  330192.0  326686.0   3506.0  54813.0
10   도봉구  348646.0  346629.0   2017.0  51312.0
11   노원구  569384.0  565565.0   3819.0  71941.0
12   은평구  494388.0  489943.0   4445.0  72334.0
13  서대문구  327163.0  314982.0  12181.0  48161.0
14   마포구  389649.0  378566.0  11083.0  48765.0
15   양천구  479978.0  475949.0   4029.0  52975.0
16   강서구  603772.0  597248.0   6524.0  72548.0
17   구로구  447874.0  416487.0  31387.0  56833.0
18   금천구  255082.0  236353.0  18729.0  32970.0
19  영등포구  402985.0  368072.0  34913.0  52413.0
20   동작구  412520.0  400456.0  12064.0  56013.0
21   관악구  525515.0  507203.0  18312.0  68082.0
22   서초구  450310.0  445994.0   4316.0  51733.0
23   강남구  570500.0  565550.0   4950.0  63167.0
24   송파구  667483.0  660584.0   6899.0  72506.0
25   강동구  453233.0  449019.0   4214.0  54622.0

In [51]:
pop_seoul['외국인 비율']=pop_seoul['외국인']/pop_seoul['인구수']*100

In [52]:
pop_seoul

      구별       인구수       한국인      외국인      고령자    외국인 비율
1    종로구  162820.0  153589.0   9231.0  25425.0  5.669451
2     중구  133240.0  124312.0   8928.0  20764.0  6.700690
3    용산구  244203.0  229456.0  14747.0  36231.0  6.038828
4    성동구  311244.0  303380.0   7864.0  39997.0  2.526635
5    광진구  372164.0  357211.0  14953.0  42214.0  4.017852
6   동대문구  369496.0  354079.0  15417.0  54173.0  4.172440
7    중랑구  414503.0  409882.0   4621.0  56774.0  1.114829
8    성북구  461260.0  449773.0  11487.0  64692.0  2.490353
9    강북구  330192.0  326686.0   3506.0  54813.0  1.061806
10   도봉구  348646.0  346629.0   2017.0  51312.0  0.578524
11   노원구  569384.0  565565.0   3819.0  71941.0  0.670725
12   은평구  494388.0  489943.0   4445.0  72334.0  0.899091
13  서대문구  327163.0  314982.0  12181.0  48161.0  3.723221
14   마포구  389649.0  378566.0  11083.0  48765.0  2.844355
15   양천구  479978.0  475949.0   4029.0  52975.0  0.839413
16   강서구  603772.0  597248.0   6524.0  72548.0  1.080540
17   구로구  447874.0  416487.0  31387.0  56833.0  7.007998
18   금천구  255082.0  236353.0  18729.0  32970.0  7.342345
19  영등포구  402985.0  368072.0  34913.0  52413.0  8.663598
20   동작구  412520.0  400456.0  12064.0  56013.0  2.924464
21   관악구  525515.0  507203.0  18312.0  68082.0  3.484582
22   서초구  450310.0  445994.0   4316.0  51733.0  0.958451
23   강남구  570500.0  565550.0   4950.0  63167.0  0.867660
24   송파구  667483.0  660584.0   6899.0  72506.0  1.033584
25   강동구  453233.0  449019.0   4214.0  54622.0  0.929765
26   NaN       NaN       NaN      NaN      NaN       NaN

In [53]:
pop_seoul.drop(26)

      구별       인구수       한국인      외국인      고령자    외국인 비율
1    종로구  162820.0  153589.0   9231.0  25425.0  5.669451
2     중구  133240.0  124312.0   8928.0  20764.0  6.700690
3    용산구  244203.0  229456.0  14747.0  36231.0  6.038828
4    성동구  311244.0  303380.0   7864.0  39997.0  2.526635
5    광진구  372164.0  357211.0  14953.0  42214.0  4.017852
6   동대문구  369496.0  354079.0  15417.0  54173.0  4.172440
7    중랑구  414503.0  409882.0   4621.0  56774.0  1.114829
8    성북구  461260.0  449773.0  11487.0  64692.0  2.490353
9    강북구  330192.0  326686.0   3506.0  54813.0  1.061806
10   도봉구  348646.0  346629.0   2017.0  51312.0  0.578524
11   노원구  569384.0  565565.0   3819.0  71941.0  0.670725
12   은평구  494388.0  489943.0   4445.0  72334.0  0.899091
13  서대문구  327163.0  314982.0  12181.0  48161.0  3.723221
14   마포구  389649.0  378566.0  11083.0  48765.0  2.844355
15   양천구  479978.0  475949.0   4029.0  52975.0  0.839413
16   강서구  603772.0  597248.0   6524.0  72548.0  1.080540
17   구로구  447874.0  416487.0  31387.0  56833.0  7.007998
18   금천구  255082.0  236353.0  18729.0  32970.0  7.342345
19  영등포구  402985.0  368072.0  34913.0  52413.0  8.663598
20   동작구  412520.0  400456.0  12064.0  56013.0  2.924464
21   관악구  525515.0  507203.0  18312.0  68082.0  3.484582
22   서초구  450310.0  445994.0   4316.0  51733.0  0.958451
23   강남구  570500.0  565550.0   4950.0  63167.0  0.867660
24   송파구  667483.0  660584.0   6899.0  72506.0  1.033584
25   강동구  453233.0  449019.0   4214.0  54622.0  0.929765

In [54]:
pop_seoul['고령자 비율']=pop_seoul['고령자']/pop_seoul['인구수']*100

In [57]:
pop_seoul.sort_values(by='외국인 비율' ,ascending=True)

      구별       인구수       한국인      외국인      고령자    외국인 비율     고령자 비율
10   도봉구  348646.0  346629.0   2017.0  51312.0  0.578524  14.717507
11   노원구  569384.0  565565.0   3819.0  71941.0  0.670725  12.634883
15   양천구  479978.0  475949.0   4029.0  52975.0  0.839413  11.036964
23   강남구  570500.0  565550.0   4950.0  63167.0  0.867660  11.072217
12   은평구  494388.0  489943.0   4445.0  72334.0  0.899091  14.631019
25   강동구  453233.0  449019.0   4214.0  54622.0  0.929765  12.051638
22   서초구  450310.0  445994.0   4316.0  51733.0  0.958451  11.488308
24   송파구  667483.0  660584.0   6899.0  72506.0  1.033584  10.862599
9    강북구  330192.0  326686.0   3506.0  54813.0  1.061806  16.600342
16   강서구  603772.0  597248.0   6524.0  72548.0  1.080540  12.015794
7    중랑구  414503.0  409882.0   4621.0  56774.0  1.114829  13.696885
8    성북구  461260.0  449773.0  11487.0  64692.0  2.490353  14.025062
4    성동구  311244.0  303380.0   7864.0  39997.0  2.526635  12.850689
14   마포구  389649.0  378566.0  11083.0  48765.0  2.844355  12.515110
20   동작구  412520.0  400456.0  12064.0  56013.0  2.924464  13.578251
21   관악구  525515.0  507203.0  18312.0  68082.0  3.484582  12.955291
13  서대문구  327163.0  314982.0  12181.0  48161.0  3.723221  14.720797
5    광진구  372164.0  357211.0  14953.0  42214.0  4.017852  11.342849
6   동대문구  369496.0  354079.0  15417.0  54173.0  4.172440  14.661322
1    종로구  162820.0  153589.0   9231.0  25425.0  5.669451  15.615404
3    용산구  244203.0  229456.0  14747.0  36231.0  6.038828  14.836427
2     중구  133240.0  124312.0   8928.0  20764.0  6.700690  15.583909
17   구로구  447874.0  416487.0  31387.0  56833.0  7.007998  12.689506
18   금천구  255082.0  236353.0  18729.0  32970.0  7.342345  12.925255
19  영등포구  402985.0  368072.0  34913.0  52413.0  8.663598  13.006191
26   NaN       NaN       NaN      NaN      NaN       NaN        NaN